
(()=>{"use strict";
const T=window.MK97_TEMPLATES||[];
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const routes={home:'index.html',templates:'templates.html',create:'poster-editor.html',projects:'projects.html',more:'more.html'};
function bottomNav(active){return `<nav class="bottomnav">${[['home','⌂','Home'],['templates','▦','Templates'],['create','＋','Create'],['projects','▧','Projects'],['more','☷','More']].map(([id,ico,label])=>`<a class="navitem ${active===id?'active':''}" href="${routes[id]}"><span>${ico}</span>${label}</a>`).join('')}</nav>`}
function injectNav(){const host=$('[data-bottomnav]'); if(host) host.outerHTML=bottomNav(document.body.dataset.nav||'');}
function toast(msg){let t=$('#mk97Toast'); if(!t){t=document.createElement('div');t.id='mk97Toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__mk97Toast);window.__mk97Toast=setTimeout(()=>t.classList.remove('show'),1500)}
function thumb(t){return `<a class="template-card" href="template-detail.html?template=${encodeURIComponent(t.id)}"><div class="poster-thumb"><div class="poster-bg bg${t.bg%8}"></div>${t.premium?'<span class="premium">♛</span>':''}<div class="thumb-copy"><span>MK97 • ${esc(t.category).toUpperCase()}</span><h3>${esc(t.name)}</h3><small>Cricket creative template</small></div></div><div class="template-meta"><b>${esc(t.name)}</b><span>${esc(t.category)}</span></div></a>`}
function renderHome(){const grid=$('#trendingTemplates');if(grid)grid.innerHTML=T.slice(0,8).map(thumb).join('')}
function renderTemplates(){const grid=$('#templateGrid');if(!grid)return;const categories=['All',...new Set(T.map(t=>t.category))];const chip=$('#categoryChips');let active='All';let query='';chip.innerHTML=categories.map(c=>`<button class="chip ${c==='All'?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');const paint=()=>{const list=T.filter(t=>(active==='All'||t.category===active)&&t.name.toLowerCase().includes(query));grid.innerHTML=list.map(thumb).join('');$('#templateCount').textContent=`${list.length} templates`};chip.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;active=b.dataset.cat;$$('[data-cat]',chip).forEach(x=>x.classList.toggle('active',x===b));paint()});$('#templateSearch').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();paint()});paint()}
function renderDetail(){const host=$('#detailPage');if(!host)return;const id=new URLSearchParams(location.search).get('template')||T[0]?.id;const t=T.find(x=>x.id===id)||T[0];$('#detailPoster').innerHTML=`<div class="poster-bg bg${t.bg%8}"></div><div class="thumb-copy"><span>MK97 • ${esc(t.category).toUpperCase()}</span><h3 style="font-size:34px">${esc(t.name)}</h3><small>Fully editable cricket design</small></div>`;$('#detailName').textContent=t.name;$('#useTemplate').href=`poster-editor.html?template=${encodeURIComponent(t.id)}`;$('#similar').innerHTML=T.filter(x=>x.category===t.category&&x.id!==t.id).slice(0,5).map(thumb).join('')}
function brandPage(){const form=$('#brandForm');if(!form)return;let brand={name:'FWCWL',accent:'#f2c45c',showLogo:true};try{brand={...brand,...JSON.parse(localStorage.getItem('mk97BrandProfile')||'{}')}}catch{};$('#brandName').value=brand.name;$('#brandAccent').value=brand.accent;$('#brandLogoToggle').classList.toggle('on',brand.showLogo);const sync=()=>{$('#brandPreviewName').textContent=$('#brandName').value||'FWCWL';document.documentElement.style.setProperty('--gold',$('#brandAccent').value)};sync();$('#brandName').addEventListener('input',sync);$('#brandAccent').addEventListener('input',sync);$('#brandLogoToggle').addEventListener('click',e=>e.currentTarget.classList.toggle('on'));form.addEventListener('submit',e=>{e.preventDefault();const data={name:$('#brandName').value.trim()||'FWCWL',accent:$('#brandAccent').value,showLogo:$('#brandLogoToggle').classList.contains('on')};localStorage.setItem('mk97BrandProfile',JSON.stringify(data));toast('Brand profile saved')})}
function openDB(){return new Promise((res,rej)=>{const req=indexedDB.open('mk97StudioAssets',1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('assets'))db.createObjectStore('assets',{keyPath:'id'})};req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function mediaPage(){const input=$('#mediaUpload');if(!input)return;const grid=$('#mediaGrid');const db=await openDB();const list=()=>new Promise((res,rej)=>{const tx=db.transaction('assets','readonly');const r=tx.objectStore('assets').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});const paint=async()=>{const items=await list();if(!items.length){grid.innerHTML='<div class="empty" style="grid-column:1/-1">No uploaded assets yet.</div>';return}grid.innerHTML=items.slice().reverse().map(a=>{const url=URL.createObjectURL(a.blob);return `<div class="asset">${a.type.startsWith('video/')?`<video src="${url}" muted></video>`:`<img src="${url}" alt="">`}<small>${esc(a.name)}</small></div>`}).join('')};input.addEventListener('change',async()=>{const files=Array.from(input.files||[]);for(const file of files){await new Promise((res,rej)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').put({id:Date.now()+'-'+Math.random(),name:file.name,type:file.type,blob:file,createdAt:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}input.value='';await paint();toast('Media added')});await paint()}
function projectsPage(){const grid=$('#projectGrid');if(!grid)return;let items=[];try{items=JSON.parse(localStorage.getItem('mk97Projects')||'[]')}catch{};if(!items.length){grid.innerHTML='<div class="empty" style="grid-column:1/-1"><div style="font-size:34px;margin-bottom:8px">▧</div>No saved projects yet.<br><a class="gold-btn" style="display:inline-flex;align-items:center;margin-top:12px" href="poster-editor.html">Create a design</a></div>';return}grid.innerHTML=items.map((p,i)=>`<a class="project-card" href="poster-editor.html"><div class="poster-thumb"><div class="poster-bg bg${i%8}"></div><div class="thumb-copy"><span>SAVED PROJECT</span><h3>${esc(p.name||'MK97 Project')}</h3></div></div><div class="project-info"><b>${esc(p.name||'Project')}</b><small>${esc(p.saved||'Saved locally')}</small></div></a>`).join('')}
function sharePage(){$$('[data-share]').forEach(b=>b.addEventListener('click',async()=>{const text='MK97 Creative Studio — cricket design ready to share.';if(navigator.share){try{await navigator.share({title:'MK97 Creative Studio',text});return}catch{}}await navigator.clipboard?.writeText(text);toast('Share text copied')}));$('#copyShare')?.addEventListener('click',async()=>{await navigator.clipboard?.writeText('MK97 Creative Studio — cricket design ready to share.');toast('Copied')})}
function morePage(){const key='mk97Theme';const set=v=>{localStorage.setItem(key,v);document.body.dataset.theme=v};set(localStorage.getItem(key)||'gold');$$('[data-theme]').forEach(b=>{b.classList.toggle('active',b.dataset.theme===localStorage.getItem(key));b.addEventListener('click',()=>{$$('[data-theme]').forEach(x=>x.classList.remove('active'));b.classList.add('active');set(b.dataset.theme);toast('Theme saved')})});$('#clearData')?.addEventListener('click',()=>{if(confirm('Clear MK97 local preview data?')){localStorage.removeItem('mk97Projects');localStorage.removeItem('mk97BrandProfile');toast('Local data cleared')}})}
document.addEventListener('DOMContentLoaded',()=>{injectNav();renderHome();renderTemplates();renderDetail();brandPage();mediaPage().catch(()=>{});projectsPage();sharePage();morePage()});
})();
