(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const T=window.MK97_TEMPLATES||[];
const store={get(k,d=null){try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function analytics(){return store.get('mk97.analytics',{templatesUsed:0,exports:0,projects:0,aiActions:0,videoEdits:0})}
function bump(k){const a=analytics();a[k]=(a[k]||0)+1;store.set('mk97.analytics',a)} window.MK97Bump=bump;
function nav(){const active=document.body.dataset.nav||'';const items=[['index.html','⌂','Home','home'],['templates.html','▦','Templates','templates'],['poster-editor.html','＋','Create','create'],['projects.html','▧','Projects','projects'],['more.html','☷','More','more']];return `<nav class="bottomnav">${items.map(([href,ico,label,key])=>`<a class="navitem ${active===key?'active':''} ${key==='create'?'create':''}" href="${href}"><span>${ico}</span>${label}</a>`).join('')}</nav>`}
$$('[data-bottomnav]').forEach(x=>x.innerHTML=nav());
function templateCard(t){return `<a class="template-card" href="template-detail.html?id=${encodeURIComponent(t.id)}"><div class="template-art" data-style="${esc(t.style)}" style="--a:${t.palette[0]};--b:${t.palette[1]};--accent:${t.palette[2]}"><span class="premium">PRO</span><div class="template-copy"><span>${esc(t.kicker)}</span><h3 style="color:${t.titleColor||'#fff'};font-family:${esc(t.font||'Montserrat')}">${esc(t.title)}</h3><small>${esc(t.detail)}</small></div></div><div class="template-meta"><strong>${esc(t.name)}</strong><em>${esc(t.category)}</em></div></a>`}
window.MK97TemplateCard=templateCard;
const trending=$('#trendingTemplates');if(trending)trending.innerHTML=T.slice(0,8).map(templateCard).join('');
const grid=$('#templateGrid'),search=$('#templateSearch'),chips=$('#categoryChips');if(grid){let cat='all';const cats=['all',...new Set(T.map(x=>x.category))];if(chips)chips.innerHTML=cats.map(c=>`<button class="chip ${c==='all'?'active':''}" data-cat="${esc(c)}">${c==='all'?'All':c.replace(/(^|-)[a-z]/g,m=>m.toUpperCase())}</button>`).join('');const render=()=>{const q=(search?.value||'').trim().toLowerCase();const list=T.filter(t=>(cat==='all'||t.category===cat)&&(!q||`${t.name} ${t.title} ${t.kicker} ${t.detail} ${t.style}`.toLowerCase().includes(q)));grid.innerHTML=list.map(templateCard).join('');const c=$('#templateCount');if(c)c.textContent=`${list.length} templates`};search?.addEventListener('input',render);chips?.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;cat=b.dataset.cat;$$('.chip',chips).forEach(x=>x.classList.toggle('active',x===b));render()});render()}
const detail=$('#templateDetail');if(detail){const id=new URLSearchParams(location.search).get('id')||store.get('mk97.selectedTemplate','match-day');const t=T.find(x=>x.id===id)||T[0];if(t){$('#detailName').textContent=t.name;$('#detailCategory').textContent=t.category.toUpperCase();$('#detailCanvas').innerHTML=templateCard(t);$('#useTemplate').addEventListener('click',()=>{store.set('mk97.selectedTemplate',t.id);bump('templatesUsed')});const sim=$('#similarTemplates');if(sim)sim.innerHTML=T.filter(x=>x.category===t.category&&x.id!==t.id).slice(0,4).map(templateCard).join('')}}
function initIntro(){const o=$('.intro-overlay');if(!o)return;if(sessionStorage.getItem('mk97.introSeen')){o.remove();return}setTimeout(()=>{o.classList.add('hide');sessionStorage.setItem('mk97.introSeen','1');setTimeout(()=>o.remove(),800)},1700)}initIntro();
if($('#textPreview')){const s=store.get('mk97.textStyle',{font:'Montserrat',size:120,spacing:0,lineHeight:.9,weight:900,align:'left',shadow:false,glow:false});const apply=()=>{const el=$('#textPreview');el.style.fontFamily=s.font;el.style.fontSize=`${Math.max(34,s.size*.42)}px`;el.style.letterSpacing=`${s.spacing*.5}px`;el.style.lineHeight=s.lineHeight;el.style.fontWeight=s.weight;el.style.textAlign=s.align;el.style.textShadow=s.glow?'0 0 20px rgba(243,201,91,.65)':(s.shadow?'0 10px 18px rgba(0,0,0,.7)':'none');$$('[data-bind]').forEach(i=>{const k=i.dataset.bind;if(i.type==='checkbox')i.checked=!!s[k];else i.value=s[k]});$$('[data-out]').forEach(o=>o.textContent=s[o.dataset.out])};$$('[data-bind]').forEach(i=>i.addEventListener(i.type==='range'?'input':'change',()=>{const k=i.dataset.bind;s[k]=i.type==='checkbox'?i.checked:(i.type==='range'||i.type==='number'?Number(i.value):i.value);store.set('mk97.textStyle',s);apply()}));apply()}
if($('#brandForm')){const b=store.get('mk97.brand',{name:'FWCWL',accent:'#f3c95b',showLogo:true});$('#brandName').value=b.name;$('#brandColor').value=b.accent;$('#brandLogoToggle').checked=b.showLogo;$('#saveBrand').onclick=()=>{b.name=$('#brandName').value;b.accent=$('#brandColor').value;b.showLogo=$('#brandLogoToggle').checked;store.set('mk97.brand',b);toast('Brand kit saved')}}
const mediaInput=$('#mediaUpload');if(mediaInput)mediaInput.addEventListener('change',()=>{const f=mediaInput.files?.[0];if(!f)return;if(f.size>3_000_000){toast('Use an image under 3 MB');return}const r=new FileReader();r.onload=()=>{store.set('mk97.pendingImage',r.result);const img=$('#uploadedPreview');if(img){img.src=r.result;img.hidden=false}toast('Image ready for Poster Studio')};r.readAsDataURL(f)});const pending=store.get('mk97.pendingImage');if(pending&&$('#uploadedPreview')){$('#uploadedPreview').src=pending;$('#uploadedPreview').hidden=false}
if($('#aiUpload')){let source=null;$('#aiUpload').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{source=r.result;$('#aiOriginal').src=source;$('#aiOriginal').hidden=false};r.readAsDataURL(f)});$('#removeBgBtn').onclick=()=>{if(!source){toast('Upload an image first');return}const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height),p=d.data,pts=[[2,2],[c.width-3,2],[2,c.height-3],[c.width-3,c.height-3]];let rr=0,gg=0,bb=0;pts.forEach(([px,py])=>{const i=(py*c.width+px)*4;rr+=p[i];gg+=p[i+1];bb+=p[i+2]});rr/=4;gg/=4;bb/=4;for(let i=0;i<p.length;i+=4){const dist=Math.hypot(p[i]-rr,p[i+1]-gg,p[i+2]-bb)/1.732;if(dist<34)p[i+3]=0;else if(dist<60)p[i+3]=Math.round(p[i+3]*(dist-34)/26)}x.putImageData(d,0,0);const url=c.toDataURL('image/png');$('#aiResult').src=url;$('#aiResult').hidden=false;store.set('mk97.pendingImage',url);bump('aiActions');toast('Cutout ready for Poster Studio')};img.src=source}}
if($('#scheduleForm')){$('#saveSchedule').onclick=()=>{store.set('mk97.schedule',{date:$('#scheduleDate').value,time:$('#scheduleTime').value,platform:$('#schedulePlatform').value});toast('Schedule saved')};$('#downloadIcs').onclick=()=>{const d=$('#scheduleDate').value.replaceAll('-',''),t=(($('#scheduleTime').value||'12:00').replace(':','')+'00');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${d}T${t}\nSUMMARY:MK97 Social Post\nDESCRIPTION:Scheduled MK97 export\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='MK97-post-schedule.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}
if($('#projectGrid')){const p=store.get('mk97.projects',[]);$('#projectGrid').innerHTML=p.length?p.map(x=>`<article class="project-card" style="padding:12px"><div class="template-art" style="--a:#07131b;--b:#45151d;--accent:#f3c95b;aspect-ratio:4/3"><div class="template-copy"><span>SAVED PROJECT</span><h3>${esc(x.name||'Cricket Design')}</h3><small>${esc(x.saved||'')}</small></div></div></article>`).join(''):`<div class="panel" style="grid-column:1/-1;text-align:center;padding:30px">No saved projects yet.<br><a class="gold-btn" href="poster-editor.html" style="margin-top:14px">Create Design</a></div>`}
if($('#analyticsMetrics')){const a=analytics();$('#analyticsMetrics').innerHTML=[['Templates Used',a.templatesUsed],['Exports',a.exports],['Saved Projects',a.projects],['AI Actions',a.aiActions]].map(([l,v])=>`<div class="metric"><strong>${v}</strong><span>${l}</span></div>`).join('')}
$$('.segmented').forEach(seg=>seg.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$$('button',seg).forEach(x=>x.classList.toggle('active',x===b))}));
function toast(msg){let t=$('#studioToast');if(!t){t=document.createElement('div');t.id='studioToast';document.body.appendChild(t)}t.textContent=msg;clearTimeout(window.__mk97Toast);window.__mk97Toast=setTimeout(()=>t.remove(),1700)}window.MK97Toast=toast;
})();